### ISSUE TITLE
hi,电信会限制对个人服务器的访问吗？

### ISSUE THREAD

**Issue by CasperCheuk** [zjq19930322/NBIot-Cloud-Server#1]
hi,电信会限制对个人服务器的访问吗？我这边可以耶，请问测试环境是怎么样的？

**Comment by pangpangshui** [comment]
你好，利用电信物联网平台提供的接口是可以的，但是单独使用电信的sim卡单独开发一个接口或者一个云平台(CoAP/UDP)是不允许的，需要电信把你的服务器ip加入白名单，之后数据的流量才会由电信的基站转发到你服务器，这样才可行。如果你那边可以要不然就是对接了电信的物联网平台，要不然你已经将你的服务器ip加进去电信的白名单了。 但是据我了解，电信不允许把个人服务器加入白名单。@CasperCheuk

**Comment by pangpangshui** [comment]
你好，利用电信物联网平台提供的接口是可以的，但是单独使用电信的sim卡单独开发一个接口或者一个云平台(CoAP/UDP)是不允许的，需要电信把你的服务器ip加入白名单，之后数据的流量才会由电信的基站转发到你服务器，这样才可行。如果你那边可以要不然就是对接了电信的物联网平台，要不然你已经将你的服务器ip加进去电信的白名单了。 @CasperCheuk

**Comment by CasperCheuk** [comment]
谢谢回复，我正好有条件，改天我也做做实验试试。

**Comment by CasperCheuk** [comment]
在下还有一要事相求，不知前辈能否简单说明一下如何部署你的系统？

**Comment by pangpangshui** [comment]
工作原因一直忙，不好意思，这两天更新。
